//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2PrintingManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongNo
    {
        public int IdCN { get; set; }
        public Nullable<double> SoTienNo { get; set; }
        public Nullable<double> SoTienTraLanTruoc { get; set; }
        public Nullable<System.DateTime> NgayTraCuoiCung { get; set; }
        public int IdKH { get; set; }
    
        public virtual KH KH { get; set; }
    }
}
